tags
I-Cellular_component
E-Gene_or_gene_product
I-Organism_subdivision
I-Organism_substance
B-Gene_or_gene_product
B-Cancer
I-Cancer
E-Pathological_formation
I-Pathological_formation
S-Organism_substance
S-Organ
E-Organ
I-Immaterial_anatomical_entity
E-Cell
I-Simple_chemical
E-Tissue
B-Organism
S-Cellular_component
S-Pathological_formation
I-Amino_acid
E-Anatomical_system
S-Developing_anatomical_structure
B-Immaterial_anatomical_entity
B-Protein
I-Chemical
S-Organism
I-Gene_or_gene_product
I-Cell
E-Multi-tissue_structure
B-Organism_subdivision
E-Cellular_component
S-Chemical
S-Protein
B-Simple_chemical
E-Organism
B-Developing_anatomical_structure
S-Multi-tissue_structure
S-Immaterial_anatomical_entity
B-Organism_substance
E-Organism_substance
E-Simple_chemical
I-Tissue
E-Immaterial_anatomical_entity
I-Organism
I-Protein
S-Organism_subdivision
E-Cancer
I-Developing_anatomical_structure
S-Tissue
E-Chemical
S-Amino_acid
O
S-Gene_or_gene_product
E-Organism_subdivision
B-Anatomical_system
B-Chemical
B-Cell
E-Developing_anatomical_structure
I-Multi-tissue_structure
B-Pathological_formation
B-Cellular_component
B-Organ
I-Anatomical_system
S-Cell
E-Amino_acid
B-Tissue
S-Simple_chemical
E-Protein
B-Multi-tissue_structure
I-Organ
S-Cancer
B-Amino_acid
S-Anatomical_system
PAD
